services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini  # <=== thêm dòng này
    environment:
      - WORDPRESS_DB_NAME=kmk_phucminhkhang
      - WORDPRESS_TABLE_PREFIX=phucminhkhang_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=sa
      - WORDPRESS_DB_PASSWORD=kmk@.123
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 8081:80
  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
      - ./kmk_phucminhkhang.sql:/docker-entrypoint-initdb.d/kmk_phucminhkhang.sql
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - MYSQL_USER=sa
      - MYSQL_ROOT_PASSWORD=kmk@.123
      - MYSQL_PASSWORD=kmk@.123 
      - MYSQL_DATABASE=kmk_phucminhkhang
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
     - 8181:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: kmk@.123
      UPLOAD_LIMIT: 100000000
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-sessions:/tmp

volumes:
  db_data:
